### ISSUE TITLE
Is there a plan to release the code?

### ISSUE THREAD

**Issue by scorpioliu** [YueWuHKUST/AniPortraitGAN#2]

**Comment by kathrinawu** [comment]
Yes, Please stay tuned!

**Comment by zimenglan-sysu-512** [comment]
will release the training code?

**Comment by SIGA23-Anoym-381** [comment]
We don't have a plan to release the training code for now.

**Comment by kathrinawu** [comment]
Sorry that we don't have a plan to release the training code for now.

**Comment by akk-123** [comment]
just a readme now??

**Comment by maocaixia** [comment]
Just talking，never release.

**Comment by kathrinawu** [comment]
For the dataset release，the SHHQ dataset's agreement restrict us to directly release the SHHQ-HS dataset，and we can only release the preprocess scripts. Since the preprocessing is complex，we're still trying to find a way to make the preprocess script convenient to use. Sorry for the late.

**Comment by kathrinawu** [comment]
code is released now.
