### ISSUE TITLE
Great work! How to generate the expression.npy\joint_eulers.npy\camera_pose.npy ? Could you share the way? Thanks! 

### ISSUE THREAD

**Issue by maocaixia** [YueWuHKUST/AniPortraitGAN#5]
@YueWuHKUST

**Comment by icekeg** [comment]
Can I use specified photos to finetune the model?

**Comment by kathrinawu** [comment]
@maocaixia 

The npy files need to be organized follows this format. Please refer to the README.md
| Keyframes | Shape | Description |
| :-: | :-: | :-: |
| Expression | [N, 64] | Coefficients of the expression PCA space in [Deep3DFaceRecon](https://github.com/sicxu/Deep3DFaceRecon_pytorch)
| Pose | [N, 6, 3] | Euler angles for SMPL joints [12, 13, 14, 15, 16, 17]
| Camera | [N, 2] | Camera yaw and pitch angles

**Comment by kathrinawu** [comment]
@icekeg 

Yes.
