### ISSUE TITLE
Create different expressions of a specified person

### ISSUE THREAD

**Issue by icekeg** [YueWuHKUST/AniPortraitGAN#6]
Can I use an existing character portrait to finetune this model and generate pictures with various expressions and different angles based on this character? Will there be any examples of this workflow later?

**Comment by kathrinawu** [comment]
This application will require some GAN inversion techniques to inverse an existing character to the latent space of the GAN model. After the latent is obtained, you can directly input various expressions and angles to generate the pictures you want.
